### ISSUE TITLE
Can't extract assets from Lose the Heat 2

### ISSUE THREAD

**Issue by TheSystemGuy1337** [n0samu/DirectorCastRipper#8]
Doubt I'm going to hear anything since this project appears to be abandoned but here goes. When I go to decompile Lose the Heat 2 with D12, I'm first greeted with a script error and no other information. I clicked yes. Then the file prompt appeared twice. Then when I went to extract the assets, it complained that the Physics Xtra was missing, and the program quit without any warning or error message.

**Comment by TheSystemGuy1337** [comment]
Managed to get it to output a log. It keeps generating an illegal CSV file which crashes Shockwave. Even if I only extract sounds (which is what I'm looking to extract)

The error is `Failed to open file. Reason: Bad file name, Path: -2147483645Casts.csv`

**Comment by n0samu** [comment]
Not abandoned, I just haven't had time to work on it! Please attach a zip file containing all of the files you were trying to extract from, and I'll take a look at some point in the future

**Comment by n0samu** [comment]
About the script error and file prompt appearing twice, I noticed that bug recently too. It only occurs on my laptop, not my desktop that I normally use for development. I still need to investigate that too.

**Comment by TheSystemGuy1337** [comment]
> Not abandoned, I just haven't had time to work on it! Please attach a zip file containing all of the files you were trying to extract from, and I'll take a look at some point in the future

[lose_the_heat_2.zip](https://github.com/user-attachments/files/18255069/lose_the_heat_2.zip)

Here are the files. I fetched them from Flashpoint, a preservation project. I'm also on Windows 11, so I may need to use Windows XP in a VM for proper compatibility if that's the case. And when the program quits, no files are even dumped. I just get a log which is often blank. Even if I tell it to only extract audio. Decompiling it back to a DIR using ProjectorRays results in the same outcome; Shockwave complains about a missing Xtra followed by crash to desktop. I'm glad this is still being worked on. Shockwave is about as rippable as Lego Island's SI files.

**Comment by TheSystemGuy1337** [comment]
@n0samu , small update. I was able to extract the assets to the game just fine under a Windows XP VM. The cast ripper did not complain about missing Xtras or generate an illegal CSV file. I suspect Windows 11 may have broke the utility.

Some files are missing, notably the title screen music and picture, but most of the assets are there.

**Comment by n0samu** [comment]
Okay I'll look into it asap. I hope it is not a Windows 11 issue because I don't have that to test. Though I may update to it soon.

**Comment by TheSystemGuy1337** [comment]
> Okay I'll look into it asap. I hope it is not a Windows 11 issue because I don't have that to test. Though I may update to it soon.

I actually thank you for making this utility standalone. It's much easier to use, even if the rips are incomplete (right now) and is a bit buggy and I'm forced to use Windows XP.

**Comment by n0samu** [comment]
This should be fixed in version 2.6. Try out the new release and let me know if you experience any further issues.

**Comment by TheSystemGuy1337** [comment]
I tried it again. It no longer errors out on Windows 11, but I'm still getting incomplete rips. Title screen music and title screen picture are still missing.

@n0samu

**Comment by TheSystemGuy1337** [comment]
[Export.log](https://github.com/user-attachments/files/31415335/Export.log)

**Comment by n0samu** [comment]
Can you tell me what cast/movie members the title screen music and image are stored in?

**Comment by n0samu** [comment]
@TheSystemGuy1337 I found the title screen music and picture, they are inside Flash member 22 of the main movie. That member is exported as an SWF file that you can open in JPEXS Decompiler to extract the music and image. Extracting from Flash movies is outside the scope of this tool.

[1_22.zip](https://github.com/user-attachments/files/31417607/1_22.zip)

**Comment by TheSystemGuy1337** [comment]
**I found 1_22. IT'S ALIVE!!!!!!**

@n0samu
